[workspace]
resolver = "2"
members = ["host", "methods"]

[workspace.dependencies]
risc0-zkvm = { version = "3.0", features = ["cuda"] }
risc0-build = "3.0"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
