# Release: https://github.com/zenopie/zkVM-test/releases/tag/v0.0.2
# Workflow URL: https://github.com/zenopie/zkVM-test/actions/runs/19835157902
# Commit: https://github.com/zenopie/zkVM-test/commit/95c9f2c4d719c1afbcb65e53177a7e7562aea764
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/zkvm-test@sha256:a2f8115a47f1897d1f82a0c8ef1c214e79711f8ea65cc905f79e059dd8ba31ee
    ports:
      - '8080'
