# Release: https://github.com/zenopie/zkVM-test/releases/tag/v0.0.1
# Workflow URL: https://github.com/zenopie/zkVM-test/actions/runs/19833766666
# Commit: https://github.com/zenopie/zkVM-test/commit/4210dacf9c9b2efbd504e4531b52b234ccf2e3c5
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/zkvm-test@sha256:5f8bdcf95708bff25720a4a9f045c150cdf091466cb199d30bb2d25b005ce65c
    ports:
      - '8080'
