[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest", "phase1-cache", "phase1a-cache-segment", "phase2-vm"]
